name: 'cpkg Upgrade'
description: 'Automatically upgrade cpkg dependencies and create a pull request'
inputs:
  token:
    description: 'GitHub token for creating pull requests'
    required: true
  pr-title:
    description: 'Title for the pull request'
    required: false
    default: 'chore: update dependencies'
  pr-body:
    description: 'Body for the pull request'
    required: false
    default: |
      Automated dependency update.
      
      This PR was created by the cpkg upgrade workflow.
  branch:
    description: 'Branch name for the pull request'
    required: false
    default: 'cpkg-upgrade-dependencies'
  commit-message:
    description: 'Commit message for the changes'
    required: false
    default: 'chore: update dependencies'
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.21'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install cpkg
      shell: bash
      run: |
        go install github.com/SCKelemen/cpkg@latest

    - name: Check for available updates
      id: check
      shell: bash
      run: |
        # Run cpkg check and capture output
        OUTPUT=$(cpkg check 2>&1 || true)
        
        # Check if there are any dependencies that can be upgraded
        # The check command prints "available" for dependencies with updates
        # and "All dependencies are up to date." when there are none
        if echo "$OUTPUT" | grep -qE "(major|minor|patch) available"; then
          echo "has_updates=true" >> $GITHUB_OUTPUT
          echo "Found outdated dependencies"
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
          echo "All dependencies are up to date"
        fi

    - name: Upgrade dependencies
      if: steps.check.outputs.has_updates == 'true'
      shell: bash
      run: |
        cpkg upgrade

    - name: Check for changes
      if: steps.check.outputs.has_updates == 'true'
      id: changes
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.check.outputs.has_updates == 'true' && steps.changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.token }}
        commit-message: ${{ inputs.commit-message }}
        title: ${{ inputs.pr-title }}
        body: ${{ inputs.pr-body }}
        branch: ${{ inputs.branch }}
        delete-branch: true

